### model
model_name_or_path: /path/to/your/model

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
deepspeed: examples/deepspeed/ds_z3_config.json

### dataset
dataset: sft_data
template: <model_template>    # e.g., qwen, llama3, etc.
cutoff_len: 8192
max_samples: 30000
overwrite_cache: true
preprocessing_num_workers: 4
dataloader_num_workers: 4

### output
output_dir: /path/to/saves
logging_steps: 1
save_strategy: epoch
plot_loss: true
overwrite_output_dir: true
save_only_model: false

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

